### PR TITLE
Added Shor's factoring algorithm example

### PR DESCRIPTION
**Pull request by AbeerVaishnav13**
Hey @tgehr, this is an example of Shor's factoring algorithm in SILQ. Hoping this gets merged with the main repo.

Regards
Abeer

### CODE REVIEW

**Comment by AbeerVaishnav13** [comment]
Hello @tgehr,
Just a reminder to add this Shor's factoring algorithm example to the repo. Hoping for it to get merged soon.

Regards
Abeer

**Comment by tjf801** [comment]
I don't see why this hasn't been merged, this is great example code.

**Comment by tgehr** [comment]
@tjf801 It has not been merged because it is not obviously correct (e.g., it does not perform any continued fraction expansion) and I have not gotten around to reviewing it in detail so far. (Also, there is some questionable type casting in the implementation.)

**Comment by tgehr** [comment]
This is my own implementation of Shor's algorithm:
https://github.com/eth-sri/silq/blob/master/test/shor.slq

@AbeerVaishnav13 It think your implementation is missing steps, it is using the result of the quantum subroutine directly as a candidate for the order. Also, I think the modular exponentiation part does not work correctly.

**Comment by AbeerVaishnav13** [comment]
Ohh yes @tgehr. Thanks for pointing it out. I definitely forgot to consider the continued fraction part in my code.

Also thanks for sharing your version of the code. It helped me clear many things regarding the implementation of Shor's factoring algorithm in Silq!

**Pull request closed without merging**
